\c coursquest_db
 -- change name of db


-- Create your seedfiles here using SQL -  INSERT INTO() VALUES()
-- Inserting user data
INSERT INTO users (name, email, is_faculty)
VALUES 
('John Doe', 'john@example.com', false),
('Jane Smith', 'jane@example.com', true);

-- Inserting course data
INSERT INTO courses (user_id, name, subject, description, professor, image_url, start_date, end_date, difficulty, cost)
VALUES 
(1, 'Introduction to Programming', 'Computer Science', 'Dive into the world of programming with this introductory course. Led by Dr. Smith, you`ll learn the fundamentals of programming, including essential concepts, syntax, and problem-solving techniques. From understanding variables and data types to mastering control structures, this course lays a solid foundation for aspiring programmers. Through hands-on exercises and projects, you`ll gain practical experience and confidence in your coding abilities. Whether you`re completely new to programming or looking to refresh your skills, this course is your gateway to the exciting field of computer science.', 'Dr. Smith', 'https://res.cloudinary.com/dvmczcg3f/image/upload/t_crop/v1711416478/CourseQuest%20-%20App/circuit_board_pic_kgsrqb.jpg', '2024-01-01', '2024-03-01', 'Beginner', 0.00),
(1, 'Data Science Fundamentals', 'Data Science', 'Embark on a journey into the realm of data science with Prof. Johnson as your guide. In this comprehensive course, you`ll explore the essential principles and techniques that underpin data analysis and machine learning. From data wrangling and visualization to predictive modeling, you`ll gain a deep understanding of how to extract valuable insights from complex datasets. Through a blend of theory and practical exercises, you`ll develop the skills needed to tackle real-world data challenges and make informed decisions. Whether you`re a beginner or an experienced analyst looking to expand your knowledge, this course equips you with the tools to thrive in the dynamic field of data science.', 'Prof. Johnson', 'https://res.cloudinary.com/dvmczcg3f/image/upload/t_crop/v1711416940/CourseQuest%20-%20App/data-plot-image-jpg_bcv5io.jpg', '2024-02-01', '2024-04-01', 'Intermediate', 29.99),
(NULL, 'Web Development Fundamentals', 'Computer Science', 'Join Dr. Brown in uncovering the building blocks of the web in this engaging course on web development fundamentals. From crafting beautiful layouts with HTML and styling them with CSS to adding interactivity with JavaScript, you`ll learn the essential skills needed to create stunning websites from scratch. Through hands-on projects and guided tutorials, you`ll gain practical experience in designing and coding web pages that are both visually appealing and functional. Whether you`re a complete novice or looking to enhance your existing skills, this course provides the perfect starting point for aspiring web developers.', 'Dr. Brown', 'https://res.cloudinary.com/dvmczcg3f/image/upload/t_crop/v1711415511/CourseQuest%20-%20App/coding-svg_cf0sgo.jpg', '2024-03-01', '2024-05-01', 'Beginner', 0.00),
(NULL, 'Machine Learning Basics', 'Machine Learning', 'Delve into the fascinating world of machine learning with Prof. Lee as your mentor. This introductory course covers the fundamental algorithms and techniques used in machine learning, from supervised and unsupervised learning to classification and regression. Through a blend of theoretical concepts and practical examples, you``ll learn how to build and train machine learning models to make predictions and uncover patterns in data. Whether you`re a novice or a seasoned professional looking to expand your skill set, this course offers a solid foundation for mastering the principles of machine learning and applying them to real-world problems.', 'Prof. Lee', 'https://res.cloudinary.com/dvmczcg3f/image/upload/t_crop/v1711418088/CourseQuest%20-%20App/network-image-jpg_ayubmd.jpg', '2024-04-01', '2024-06-01', 'Intermediate', 49.99),
(NULL, 'Digital Marketing Essentials', 'Marketing', 'Explore the dynamic world of digital marketing with Dr. White in this comprehensive course. From search engine optimization (SEO) and content marketing to social media advertising, you`ll learn the essential strategies and tactics needed to succeed in today`s digital landscape. Through case studies and practical exercises, you`ll gain hands-on experience in developing and executing effective digital marketing campaigns that drive results. Whether you`re a marketing professional seeking to enhance your skills or an entrepreneur looking to promote your business online, this course provides invaluable insights into the principles and practices of digital marketing.', 'Dr. White', 'https://res.cloudinary.com/dvmczcg3f/image/upload/c_crop,ar_16:9/v1711418541/CourseQuest%20-%20App/marketing-strateg-pic-jpg_pgzkzi.jpg', '2024-05-01', '2024-07-01', 'Beginner', 19.99),
(1, 'Introduction to Drawing', 'Art', 'Unleash your creativity and master the art of drawing with Prof. Davis as your guide. This introductory course covers the fundamental techniques and principles of drawing, from understanding line and shape to capturing light and shadow. Through a series of guided exercises and projects, you`ll develop your observational skills and learn how to render objects and scenes with accuracy and expression. Whether you`re a complete beginner or an experienced artist looking to refine your skills, this course offers a supportive environment to explore your artistic potential and unlock the joys of drawing.', 'Prof. Davis', 'https://res.cloudinary.com/dvmczcg3f/image/upload/t_crop/v1711418337/CourseQuest%20-%20App/drawing-of-hands-jpg_kgiyip.jpg', '2024-06-01', '2024-08-01', 'Beginner', 0.00),
(1, 'Art History', 'Art', 'Journey through the rich tapestry of art history with Dr. Rodriguez as your expert companion. This in-depth course traces the evolution of art from ancient civilizations to the modern era, exploring major movements, styles, and artists along the way. From the Renaissance masters to the avant-garde pioneers, you`ll gain a deeper understanding of the cultural, political, and social contexts that have shaped the course of art history. Through lectures, discussions, and visual analyses, you`ll cultivate a critical eye and develop a comprehensive appreciation for the diverse expressions of human creativity throughout the ages.', 'Dr. Rodriguez', 'https://res.cloudinary.com/dvmczcg3f/image/upload/c_crop,ar_16:9/v1711418248/CourseQuest%20-%20App/weaving-cloth-pic-jpg_zauofc.jpg', '2024-07-01', '2024-09-01', 'Intermediate', 39.99),
(1, 'Photography Basics', 'Art', 'Capture the beauty of the world around you with Prof. Martinez in this engaging course on photography basics. From mastering camera settings and composition to understanding light and exposure, you`ll learn the essential skills needed to take stunning photographs in any setting. Through hands-on exercises and feedback sessions, you`ll develop your artistic vision and technical proficiency, allowing you to express yourself creatively through the medium of photography. Whether you`re an aspiring photographer or a hobbyist looking to improve your skills, this course provides a solid foundation for unleashing your photographic potential and capturing memorable moments with confidence.', 'Prof. Martinez', 'https://res.cloudinary.com/dvmczcg3f/image/upload/c_crop,ar_16:9/v1711416707/CourseQuest%20-%20App/photo-of-films-jpeg_dmk0xf.jpg', '2024-08-01', '2024-10-01', 'Beginner', 29.99);

-- Inserting reviews data
INSERT INTO reviews (user_id, course_id, rating, review)
VALUES 
(1, 1, 5, 'Great course! I learned a lot.'),
(1, 2, 4, 'Enjoyed the content, but could use more exercises.'),
(1, 3, 4, 'Great introduction to web development.'),
(1, 4, 5, 'Excellent course on machine learning concepts.'),
(1, 5, 3, 'Informative content, but could use more practical examples.'),
(1, 6, 4, 'Great course! Covers the basics of drawing thoroughly.'),
(1, 7, 5, 'Fascinating exploration of art history.'),
(1, 8, 4, 'Enjoyed learning photography basics with this course.');
